[features]
seeds = false
[programs.devnet]
currency_coin = "A3mhZsPAjroa8oQokfjGKNNNrKwbpz5ZwszHduYs6hz6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hedgehog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create-mint-auth = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-mint-auth.ts"
create-mints = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-mints.ts"
create-metadatas = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-metadatas.ts"
init-owner-atas = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-owner-atas.ts"
init-atas = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-atas.ts"
init-circulation = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-circulation.ts"
init-pool0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-pool0.ts"
fetch-state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fetch-state.ts"
